### ISSUE TITLE
Error on retrieve issue list

### ISSUE THREAD

**Issue by kosz78** [mx-bernhard/keypirinha-youtrack#1]
Returns the following error on retrieve issue list:
```
13:25:27.783 WARNING: Ignoring suggested item with invalid property(ies) from plugin youtrack.YouTrack (category: #1002; label: ""; target: "")
13:25:32.158 Python: Traceback (most recent call last):
13:25:32.158 Python:   File "C:\Users\kostya\keypirinha\Profile\InstalledPackages\youtrack.keypirinha-package\youtrack.py", line 193, in youtrack_intellisense_legacy
13:25:32.158 Python:   File "C:\Users\kostya\keypirinha\Profile\InstalledPackages\youtrack.keypirinha-package\youtrack.py", line 221, in get_as_xml
13:25:32.158 Python:   File "lib\xml\dom\minidom.py", line 1968, in parseString
13:25:32.158 Python:   File "lib\xml\dom\expatbuilder.py", line 925, in parseString
13:25:32.158 Python:   File "lib\xml\dom\expatbuilder.py", line 223, in parseString
13:25:32.158 Python: xml.parsers.expat.ExpatError: syntax error: line 1, column 0
13:25:32.158 Python:
13:25:32.158 Python: During handling of the above exception, another exception occurred:
13:25:32.158 Python: Traceback (most recent call last):
13:25:32.158 Python:   File "C:\Users\kostya\keypirinha\Profile\InstalledPackages\youtrack.keypirinha-package\youtrack.py", line 440, in on_suggest
13:25:32.158 Python:   File "C:\Users\kostya\keypirinha\Profile\InstalledPackages\youtrack.keypirinha-package\youtrack.py", line 103, in on_suggest
13:25:32.158 Python:   File "C:\Users\kostya\keypirinha\Profile\InstalledPackages\youtrack.keypirinha-package\youtrack.py", line 127, in add_filter_suggestions
13:25:32.158 Python:   File "C:\Users\kostya\keypirinha\Profile\InstalledPackages\youtrack.keypirinha-package\youtrack.py", line 170, in fetch_suggestions
13:25:32.158 Python:   File "C:\Users\kostya\keypirinha\Profile\InstalledPackages\youtrack.keypirinha-package\youtrack.py", line 215, in youtrack_intellisense_legacy
13:25:32.158 Python: AttributeError: 'YouTrackServer' object has no attribute 'warn'
```

**Comment by kosz78** [comment]
Invalid, i use old version of plugin
